discord:
  logchannel: ${LOG_CHANNEL_ID}
  rafflechannel: ${RAFFLE_CHANNEL_ID}
  guildid: ${GUILD_ID}
  token: ${DISCORD_BOT_TOKEN}
  roles:
    admin: ${ADMIN_ROLES}

spring:
  application:
    name: teller-bot
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:${CLEARDB_ORANGE_URL}
    hikari:
      max-lifetime: 50000
      maximum-pool-size: 10
      pool-name: ticket-bot-pool
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

server:
  port: ${PORT:8080}

